Client connected WebSocket {
  domain: null,
  _events: { close: [Function] },
  _eventsCount: 1,
  _maxListeners: undefined,
  readyState: 1,
  bytesReceived: 0,
  extensions: 
   { 'permessage-deflate': 
      PerMessageDeflate {
        _options: {},
        _isServer: true,
        _inflate: null,
        _deflate: null,
        params: {},
        _maxPayload: 104857600,
        threshold: 1024 } },
  protocol: '',
  _binaryType: 'nodebuffer',
  _finalize: { [Function: bound finalize] __ultron: 1 },
  _finalizeCalled: false,
  _closeMessage: null,
  _closeTimer: null,
  _closeCode: null,
  _receiver: 
   Receiver {
     binaryType: 'nodebuffer',
     extensions: { 'permessage-deflate': [Object] },
     maxPayload: 104857600,
     bufferedBytes: 0,
     buffers: [],
     compressed: false,
     payloadLength: 0,
     fragmented: 0,
     masked: false,
     fin: false,
     mask: null,
     opcode: 0,
     totalPayloadLength: 0,
     messageLength: 0,
     fragments: [],
     cleanupCallback: null,
     hadError: false,
     dead: false,
     loop: false,
     onmessage: [Function],
     onclose: [Function],
     onerror: [Function],
     onping: [Function],
     onpong: [Function],
     state: 0 },
  _sender: 
   Sender {
     perMessageDeflate: 
      PerMessageDeflate {
        _options: {},
        _isServer: true,
        _inflate: null,
        _deflate: null,
        params: {},
        _maxPayload: 104857600,
        threshold: 1024 },
     _socket: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        destroyed: false,
        _bytesDispatched: 175,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _server: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 4241,
        parser: null,
        on: [Function],
        _paused: false,
        read: [Function],
        _consuming: true },
     firstFragment: true,
     compress: false,
     bufferedBytes: 0,
     deflating: false,
     queue: [],
     onerror: [Function] },
  _socket: 
   Socket {
     connecting: false,
     _hadError: false,
     _handle: 
      TCP {
        bytesRead: 506,
        _externalStream: {},
        fd: 20,
        reading: true,
        owner: [Circular],
        onread: [Function: onread],
        onconnection: null,
        writeQueueSize: 0 },
     _parent: null,
     _host: null,
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: true,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: 
      { end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        drain: [Object],
        timeout: [Function],
        error: [Object],
        close: [Object],
        data: [Object] },
     _eventsCount: 8,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 1,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     allowHalfOpen: true,
     destroyed: false,
     _bytesDispatched: 175,
     _sockname: null,
     _pendingData: null,
     _pendingEncoding: '',
     server: 
      Server {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        _connections: 7,
        _handle: [Object],
        _usingSlaves: false,
        _slaves: [],
        _unref: false,
        allowHalfOpen: true,
        pauseOnConnect: false,
        httpAllowHalfOpen: false,
        timeout: 120000,
        _pendingResponseData: 0,
        _connectionKey: '6::::3000' },
     _server: 
      Server {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        _connections: 7,
        _handle: [Object],
        _usingSlaves: false,
        _slaves: [],
        _unref: false,
        allowHalfOpen: true,
        pauseOnConnect: false,
        httpAllowHalfOpen: false,
        timeout: 120000,
        _pendingResponseData: 0,
        _connectionKey: '6::::3000' },
     _idleTimeout: -1,
     _idleNext: null,
     _idlePrev: null,
     _idleStart: 4241,
     parser: null,
     on: [Function],
     _paused: false,
     read: [Function],
     _consuming: true },
  _ultron: 
   Ultron {
     id: 1,
     ee: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        destroyed: false,
        _bytesDispatched: 175,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _server: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 4241,
        parser: null,
        on: [Function],
        _paused: false,
        read: [Function],
        _consuming: true } },
  protocolVersion: 13,
  maxPayload: 104857600,
  upgradeReq: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: null,
        ended: true,
        endEmitted: false,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: true,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: true,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     socket: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        destroyed: false,
        _bytesDispatched: 175,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _server: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 4241,
        parser: null,
        on: [Function],
        _paused: false,
        read: [Function],
        _consuming: true },
     connection: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        destroyed: false,
        _bytesDispatched: 175,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _server: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 4241,
        parser: null,
        on: [Function],
        _paused: false,
        read: [Function],
        _consuming: true },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { host: '127.0.0.1:3000',
        connection: 'Upgrade',
        pragma: 'no-cache',
        'cache-control': 'no-cache',
        upgrade: 'websocket',
        origin: 'http://127.0.0.1:3000',
        'sec-websocket-version': '13',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36',
        'accept-encoding': 'gzip, deflate, sdch, br',
        'accept-language': 'en-US,en;q=0.8',
        'sec-websocket-key': 'reJ4LfBgATj4mTFqjHDTeA==',
        'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits' },
     rawHeaders: 
      [ 'Host',
        '127.0.0.1:3000',
        'Connection',
        'Upgrade',
        'Pragma',
        'no-cache',
        'Cache-Control',
        'no-cache',
        'Upgrade',
        'websocket',
        'Origin',
        'http://127.0.0.1:3000',
        'Sec-WebSocket-Version',
        '13',
        'User-Agent',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36',
        'Accept-Encoding',
        'gzip, deflate, sdch, br',
        'Accept-Language',
        'en-US,en;q=0.8',
        'Sec-WebSocket-Key',
        'reJ4LfBgATj4mTFqjHDTeA==',
        'Sec-WebSocket-Extensions',
        'permessage-deflate; client_max_window_bits' ],
     trailers: {},
     rawTrailers: [],
     upgrade: true,
     url: '/',
     method: 'GET',
     statusCode: null,
     statusMessage: null,
     client: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        destroyed: false,
        _bytesDispatched: 175,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _server: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 4241,
        parser: null,
        on: [Function],
        _paused: false,
        read: [Function],
        _consuming: true },
     _consuming: false,
     _dumped: false,
     parser: null },
  _isServer: true }