module.exports = {
  default_user: {
    type: 'user',
    username: '',
    editName: '',
    password: '',
    sessionId: '',
    room: null,
    seat: null,
    loggedIn: false,
    logout: false,
    accountCash: 0,
    getCash: false,
    tableCash: 0,
    getTableCash: 0,
    getCashWait: 0,
    rejoinWaitTimer: 0,
    message: '',
    chats: [],
    update: 'nothing to report',
    dcRound: 0,
    dcRemain: 1,
    inFilter: [],
    outFilter: [],
    post: 0,
    check: false,     
    fold: false,
    bet: 0,
    call: 0,
    raise: 0,
    reRaise: 0,
    addToPot: 0,
    show: false,
    muck: false,
    holeCards: [],
    sitOut: false,
    joinTable: false,
    leaveTable: false,
    disconnect: false,
    highFiveIndexes: [],
    seat1: {},
    seat2: {},
    seat3: {},
    seat4: {},
    seat5: {},
    seat6: {},
    seat7: {},
    seat8: {},
    seat9: {},
    seat10: {},
    filters: {
      in: {
        editName: true,
        password: true,
        getCash: true,
        getTableCash: true,
        joinTable: true,
        message: true,
        logout: true,
        disconnect: true,
      },
      out: {
        username: true,
        loggedIn: true,
        code: true,
        status: true,
        room: true,
        seat: true,
        dealer: true,
        turn: true,
        accountCash: true,
        tableCash: true,
        chats: true,
        update: true,
        rejoinWaitTimer: true,
        holeCards: true,
        dcRound: true,
        dcRemain: true,
        seat1: true,
        seat2: true,
        seat3: true,
        seat4: true,
        seat5: true,
        seat6: true,
        seat7: true,
        seat8: true,
        seat9: true,
        seat10: true,
      },
    },
  },
  dbUser: {
    username: '',

  },
  lobby: {
    name: 'LOBBY',
    type: 'lobby',
  },
  table1: {
    type: 'table',
    name: 'TABLE1',
    pollTimer: 2000,
    winner: null,
    pollForStartTimer: null,
    checkedBet: 0,
    // currentBet: 0,  // need to compare bet against currentBet to start sidePots
    addToPot: 0,
    pots: [{ 
      value: 0,
      callAmount: 0,
      sidePot: false,
      nextPotIndex: null,
      playersInPot: {}, //   { seat: { playerName: username, holeCards: [hole cards], }
      time: null,
      communityCards: [], 
    }],
    filters: {
      in: {
        default: {
          clientReady: true,
          message: true,
          leaveTable: true,
          disconnect: true,
        },
      },
    },
    emptySeats: [1,2,3,4,5,6,7,8,9,10],
    leaveQueue: [],
    leaveQueueHash: {},
    joinQueue: [],
    joinQueueHash: {},
    disconnectQueue: [],
    disconnectQueueHash: {},
    seat: { // empty = null for takeSeats()
      1: null,
      2: null,
      3: null,
      4: null,
      5: null,
      6: null,
      7: null,
      8: null,
      9: null,
      10: null,
    },
  },
  state: {
    dealer: null,
    deck: [],
    communityCards: [],
    smallBlindSeat: null,
    bigBlindSeat: null,
    smallBlindAmount: 10,
    bigBlindAmount: 20,
    playersInHand: 0,
    calledBet: 0,
    round: 0,
    roundNames: {
      1: 'Pre-Flop',
      2: 'Flop',
      3: 'Turn',
      4: 'River',
      5: 'Select Winner',
    },
    turn: 1,
    expectIn: {
      call: true,
      bet: true,
      fold: true,
    },
    filters: {
      onTurn: {
        fold: true,
      },
      smallBlind: {
        post: true,
      },
      otherPlayerOut: {
        username: true,
        tableCash: true,
        playerAction: true,
        playerState: true,
      }
    },
    waitForTurn: null,
    turnTimer: 2000,
    waitBetweenHands: null,
    waitBetweenHandsTimer: 2000,
    waitForTransitions: null,
    transitionsTimer: 1000,
    seat: { // empty = null for takeSeats()  
      1: null, // seats are player.attributes reference
      2: null,
      3: null,
      4: null,
      5: null,
      6: null,
      7: null,
      8: null,
      9: null,
      10: null,
    },
  }
}

